package handler.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-03-20T15:32:19.967+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://server.handler/", name = "BusinessService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface BusinessService {

    @WebResult(name = "return", targetNamespace = "http://server.handler/", partName = "return")
    @Action(input = "http://server.handler/BusinessService/echoRequest", output = "http://server.handler/BusinessService/echoResponse")
    @WebMethod
    public People echo(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );
}
