package handler.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-03-20T15:32:20.080+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "HandlerService", 
                  wsdlLocation = "http://localhost:9527/handlerServer?wsdl",
                  targetNamespace = "http://server.handler/") 
public class HandlerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.handler/", "HandlerService");
    public final static QName BusinessServicePort = new QName("http://server.handler/", "BusinessServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9527/handlerServer?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HandlerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9527/handlerServer?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HandlerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HandlerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HandlerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HandlerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HandlerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HandlerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BusinessService
     */
    @WebEndpoint(name = "BusinessServicePort")
    public BusinessService getBusinessServicePort() {
        return super.getPort(BusinessServicePort, BusinessService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BusinessService
     */
    @WebEndpoint(name = "BusinessServicePort")
    public BusinessService getBusinessServicePort(WebServiceFeature... features) {
        return super.getPort(BusinessServicePort, BusinessService.class, features);
    }

}
