
package handler.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "handler", targetNamespace = "handler.ws")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Handler {


    /**
     * 
     * @param arg0
     * @return
     *     returns WEBSERVICE_CLIENT.People
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "handler.ws/handler/echoRequest", output = "handler.ws/handler/echoResponse")
    public People echo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
