
package handler.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "handlerService", targetNamespace = "handler.ws", wsdlLocation = "http://localhost:9527/handlerServer?wsdl")
public class HandlerService
    extends Service
{

    private final static URL HANDLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException HANDLERSERVICE_EXCEPTION;
    private final static QName HANDLERSERVICE_QNAME = new QName("handler.ws", "handlerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9527/handlerServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HANDLERSERVICE_WSDL_LOCATION = url;
        HANDLERSERVICE_EXCEPTION = e;
    }

    public HandlerService() {
        super(__getWsdlLocation(), HANDLERSERVICE_QNAME);
    }

    public HandlerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HANDLERSERVICE_QNAME, features);
    }

    public HandlerService(URL wsdlLocation) {
        super(wsdlLocation, HANDLERSERVICE_QNAME);
    }

    public HandlerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HANDLERSERVICE_QNAME, features);
    }

    public HandlerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HandlerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Handler
     */
    @WebEndpoint(name = "handlerPort")
    public Handler getHandlerPort() {
        return super.getPort(new QName("handler.ws", "handlerPort"), Handler.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Handler
     */
    @WebEndpoint(name = "handlerPort")
    public Handler getHandlerPort(WebServiceFeature... features) {
        return super.getPort(new QName("handler.ws", "handlerPort"), Handler.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HANDLERSERVICE_EXCEPTION!= null) {
            throw HANDLERSERVICE_EXCEPTION;
        }
        return HANDLERSERVICE_WSDL_LOCATION;
    }

}
